### ISSUE TITLE
The link of pretrained weight

### ISSUE THREAD

**Issue by gaowq2017** [luyvlei/BiSMAPs#1]
Hi Lu
    Thanks for sharing the code. Can you share the link of pretrained weight file and Readme file?
    Thank you!

**Comment by luyvlei** [comment]
I am uploading the stylized dataset and weight files to the network disk,
and I expect to finish the GTA5 files by the end of this month. And the
readme file will also be updated after I test the code.

gaowq2017 ***@***.***> 于2022年8月26日周五 14:34写道：
