### ISSUE TITLE
How to compute category entropy ec

### ISSUE THREAD

**Issue by gaowq2017** [luyvlei/BiSMAPs#2]
Hi Lu, thanks for sharing the code
    I don't know how to compute category entropy in source_transferability_map.py file. In paper formula (8) that Ec denotes the mean entropy of category c in the target domain. But the Ec value is seted to constant in source_transferability_map.py
Can you sharing the conpute code? 
BTW The pretrained download link can't open and download as follow:
![image](https://user-images.githubusercontent.com/29697367/188570693-a1651caf-21e9-4a8d-a2ba-dc34f446dd69.png)

Thanks

**Comment by luyvlei** [comment]
I have checked the download link and the files can be downloaded normally. It could be an intermittent problem.

The category entropy only needs to be inferred on the Cityscape dataset using the Warmup model and keeped constant. The entropy value has been written to the source file and does not need to be recalculated.

**Comment by gaowq2017** [comment]
> I have checked the download link and the files can be downloaded normally. It could be an intermittent problem.
> 
> The category entropy only needs to be inferred on the Cityscape dataset using the Warmup model and keeped constant. The entropy value has been written to the source file and does not need to be recalculated.

OK, i am get it and the download link is ok now, Thank you very much!
