### ISSUE TITLE
Data pre-processing of the cityspace

### ISSUE THREAD

**Issue by yangH8** [luyvlei/BiSMAPs#4]
We're just going to run "python3 test.py --config ./configs/gta5_test.yml ".
How can we handle the raw data downloaded from the official website of CitySpace?

**Comment by luyvlei** [comment]
The validation set downloaded on the official website of CitySpace can be directly processed by this script without additional formatting operations. Just organize folders in the following format:
```
├── dataset/
│   ├── CityScape/     
|   |   ├── gtFine/
|   |   ├── leftImg8bit/
```
