### ISSUE TITLE
运行inference.py时出错

### ISSUE THREAD

**Issue by zhang-pan** [luyvlei/BiSMAPs#5]
FileNotFoundError: [Errno 2] No such file or directory: 'inference_pseudolabels_2/CityScape\\leftImg8bit\\train\\erfurt\\erfurt_000021_000019_leftImg8bit_color.png'

请问inference_pseudolabels_2/这个文件夹下的图像数据时怎么产生的？请大佬百忙之中给予指导。

**Comment by luyvlei** [comment]
你的运行环境是windows还是linux呢，我推测是windows下的路径格式问题导致这个问题，因为你这边的斜杠是反斜杠“\”

该文件用于模型推理生成“伪”标签，我在linux下测试了一下可以正常运行
`
python3 inference.py --config ./configs/inference.yml --checkpoint_path ./runs/gta5_dill_1/from_gta5_to_cityscapes_on_deeplabv3_plus_best_model.pkl --save_path pseudolabels_dill
`

**Comment by zhang-pan** [comment]
这个路径可以在哪个文件中修改呢？我找了半天没找到，辛苦大佬指导，万分感谢

**Comment by luyvlei** [comment]
> 这个路径可以在哪个文件中修改呢？我找了半天没找到，辛苦大佬指导，万分感谢

主要修改inference.py中的第48行，name = name.split('/')[-1]，这里使用斜杠识别出路径中的最后一段，预期是从‘CityScape\leftImg8bit\train\erfurt\erfurt_000021_000019_leftImg8bit_color.png’这个字符串中切出’erfurt_000021_000019_leftImg8bit_color.png‘，你可以尝试调整下。
比较简单的方法是改成
`
name = name.split('\\')[-1]
`

**Comment by zhang-pan** [comment]
感谢大佬，您太强了。我现在是在读学生，希望在不打扰您的前提下有机会能向您请教。

**Comment by zhang-pan** [comment]
刚才的问题已经解决了
