### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by newcherryberry** [luyvlei/BiSMAPs#7]
Hi Luyvlei,
So sorry if this is a bad repo to do this on, but I cannot find another way to contact you! I need some help with a project you have worked on before (OpenAnimate)- I tried to get my friend to message you on WeChat but cannot reach you. Please let me know if I can email you or if you feel more comfortable emailing me. 
Thanks, 
Maylin

**Comment by luyvlei** [comment]
Sure, here is my e-mail: luyvlei@163.com
